# Generated by Django 4.0.2 on 2022-07-18 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('twtr', '0002_twt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='twt',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='twt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='twts', to=settings.AUTH_USER_MODEL),
        ),
    ]
